[build]
  command = "npm run build"
  publish = ".svelte-kit/output/client"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run build"
  targetPort = 5173
  functionsPort = 9999
